FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD=asdf
ENV MYSQL_DATABASE=bazaar
ENV collation-server=utf8_unicode_ci

# COPY sourceAddress.sql /db/
# COPY sourceAddress.csv /db/
# COPY tempSeed.sql /db/
# COPY jobs.sql /db/
# COPY tasks.sql /db/
# COPY seed.sql /db/

# RUN mysql -u root -p0109 jobcrawler < /docker-entrypoint-initdb.d/sourceAddress.sql
# RUN mysql -u root -p0109 jobcrawler < /usr/db/sa.csv

